Extended script to with parameter to submit a specific commit sha to be downloaded and installed.
b01/dl-vscode-server pull request #23
Opened 2024-07-15 05:01 UTC by happymab

2024-09-05 00:13 UTC, b01 requested changes
Sorry for the wait, This 1 change and it should be good to merge.

2024-09-05 00:13 UTC, b01 commented on download-vs-code.sh
> +        exit 1
Can you move this if block outside the else and below. That way it will throw an error if you try to enter an empty commit as well.

2024-10-15 22:57 UTC, ofek commented
I would love to see this merged.

2024-10-16 18:45 UTC, b01 approved these changes

2024-10-16 18:46 UTC, merged